### ISSUE TITLE
dsmr_datalogger keeps restarting every couple of seconds

### ISSUE THREAD

**Issue by wivaku** [xirixiz/dsmr-reader-docker#110]
After starting, `dsmr_datalogger` keeps crashing+restarting every few seconds. As a result, no telegrams are read.
Any suggestions?

When monitoring the serial port manually everything looks fine: I do see a telegram every 10 seconds (`screen /dev/ttyUSB0 115200`). Using Kaifa MA105C (using v4).

Using Raspberry PI 4 (`Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`), and Docker image: `xirixiz/dsmr-reader-docker:arm32v6`. Running Docker as root, but have added Dialout group to be sure (`sudo usermod -aG dialout $(whoami)`).

Load, memory etc. all look fine. Running Home Assistant on the same Raspberry Pi.  
The below shows the log:

```
dsmr      | 2020-04-27 12:27:02,418 INFO spawned: 'dsmr_datalogger' with pid 186
dsmr      | 2020-04-27 12:27:03,460 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr      | 2020-04-27 12:27:05,010 INFO exited: dsmr_datalogger (exit status 0; expected)
dsmr      | 2020-04-27 12:27:05,560 INFO spawned: 'dsmr_datalogger' with pid 188
dsmr      | 2020-04-27 12:27:06,606 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr      | 2020-04-27 12:27:08,258 INFO exited: dsmr_datalogger (exit status 0; expected)
dsmr      | 2020-04-27 12:27:08,716 INFO spawned: 'dsmr_datalogger' with pid 190
dsmr      | 2020-04-27 12:27:09,768 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr      | 2020-04-27 12:27:11,314 INFO exited: dsmr_datalogger (exit status 0; expected)
dsmr      | 2020-04-27 12:27:11,871 INFO spawned: 'dsmr_datalogger' with pid 192
dsmr      | 2020-04-27 12:27:12,905 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr      | 2020-04-27 12:27:14,424 INFO exited: dsmr_datalogger (exit status 0; expected)
```

My docker-compose: 
```
version: '3.6'

services:
  dsmrdb:
    image: postgres:10-alpine
    container_name: dsmrdb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:arm32v6
    container_name: dsmr
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr/backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DSMRREADER_LOGLEVEL=DEBUG
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
