### ISSUE TITLE
Password keep changing back to default

### ISSUE THREAD

**Issue by zuidwijk** [xirixiz/dsmr-reader-docker#129]
My password to login the web gui keeps changing back to default. Is that common?

This is my docker compose:
````YAML
version: '3.6'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
      - /dev/:/dev/:ro
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=true
      - SD_AUTORESTART_MQTT=true
    ports:
      - 7777:80
      - 7779:443
    labels:
      - traefik.backend=xxxx
      - traefik.frontend.rule=Host:xxxx
      - traefik.frontend.entrypoint=https
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=80

networks:
    default:
        external:
            name: traefik
````

Every time I change it back, yet after a while it changes back to default.

Can I add this to the environment section?:
````YAML
      - DSMR_USER=<another username>
      - DSMR_PASSWORD=<my password>
````
