### ISSUE TITLE
Database troubles after update to 4.5

### ISSUE THREAD

**Issue by sanderpleijers** [xirixiz/dsmr-reader-docker#139]
My upgrade to version 4.5 fails with this error. It seems some kind of database issue?

> File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 204, in __getitem__
    self.ensure_defaults(alias)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 172, in ensure_defaults
    conn = self.databases[alias]
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 160, in databases
    if DEFAULT_DB_ALIAS not in self._databases:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/dsmr/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 204, in __getitem__
    self.ensure_defaults(alias)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 172, in ensure_defaults
    conn = self.databases[alias]
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 160, in databases
    if DEFAULT_DB_ALIAS not in self._databases:
TypeError: argument of type 'NoneType' is not iterable

I use:
```
 dsmrdb:
    image: postgres:12-alpine
    container_name: dsmrdb
    volumes:
      - /volume2/docker/dsmr/dsmrdb:/var/lib/postgresql/data
      - /volume2/docker/dsmr/dsmrdb_backups:/dsmr/backups
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    networks:
      - backend

  dsmr:
    build:
      context: .
      dockerfile: DockerfileDSMR
    image: xirixiz/dsmr-reader-docker:latest-amd64
    container_name: dsmr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/dsmr/dsmrdb_backups:/dsmr/backups
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    environment:
      #Required:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      
      #Nginx related:
      - ENABLE_HTTP_AUTH=false
      - HTTP_AUTH_USERNAME=
      - HTTP_AUTH_PASSWORD=

      #Supervisord related:
      - SD_LOGLEVEL=info
      - SD_USER=root
      - SD_GROUP=root
      
      #Remote DSMR datalogger related (more info: https://dsmr-reader.readthedocs.io/nl/v4/installation/datalogger.html)
      - SD_AUTOSTART_DATALOGGER=true # Set to false if datalogger is running on another container
      - SD_AUTORESTART_DATALOGGER=true # Set to false if datalogger is running on another container
      - DATALOGGER_INPUT_METHOD=ipv4           # Required. Only serial or ipv4 (network) are valid values
      ##################################################################################################################
      - DATALOGGER_SERIAL_PORT=/dev/ttyUSB0 # Required if the input method is set to serial
      - DATALOGGER_SERIAL_BAUDRATE=115200   # Required if the input method is set to serial
        ##################################################################################################################
      - DATALOGGER_NETWORK_HOST=192.168.1.52     # Required if the input method is set to ipv4
      - DATALOGGER_NETWORK_PORT=8082          # Required if the input method is set to ipv4 (Docker port)
      ##################################################################################################################
      - DATALOGGER_TIMEOUT=60               # Optional. In seconds
      - DATALOGGER_SLEEP=60                  # Optional. In seconds
      - DATALOGGER_DEBUG_LOGGING=true      # Optional.
      #- SD_AUTOSTART_BACKEND=true
      #- SD_AUTORESTART_BACKEND=true
      #- SD_AUTOSTART_CLIENT=true
      #- SD_AUTORESTART_CLIENT=true

      #DSMR related (defaults are shown as value):
      - DSMR_AUTO_UPDATE=false
      - DSMR_USER=admin             # Webinterface user
      - DSMR_PASSWORD=snip         # Webinterface user
      - DSMRREADER_LOGLEVEL=WARNING # Valid values are WARNING, INFO, DEBUG
      #- DSMRREADER_PLUGINS=dsmr_plugins.modules.plugin_name1,dsmr_plugins.modules.plugin_name2
      - SECRET_KEY='snip'

      #DB related (defaults are shown as value):
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=dsmrreader
      - DB_USER=dsmrreader
      - DB_PASS=dsmrreader
      - DB_HOST=dsmrdb
      - DB_PORT=5432
      - CONN_MAX_AGE=60
    ports:
      - 7777:80
      - 7779:443
    #devices:
    #  - /dev/ttyUSB-P1METER:/dev/ttyUSB10
    networks:
      - backend
```

My Dockerfile:
```
FROM xirixiz/dsmr-reader-docker:latest-amd64

#CUSTOM
ENV DJANGO_X_FRAME_OPTIONS 'ALLOWALL'

ENV SECRET_KEY 'snip'
ENV DB_ENGINE django.db.backends.postgresql

ENV DB_NAME dsmrreader
ENV DB_USER dsmrreader
ENV DB_PASS dsmrreader

ENV DB_HOST dsmrdb
ENV DB_PORT 5432

ENV DSMR_USER admin
ENV DSMR_PASSWORD snip

#ENV DSMR_RELEASE latest
ENV DATALOGGER_MODE standalone

ENV SD_LOGLEVEL info
ENV SD_USER root
ENV SD_GROUP root

#COPY ./dsmr/ /dsmr

RUN apk --update add --no-cache \
    bash \
    curl \
    nginx \
    openssl \
    postgresql-client \
    tzdata \
    jq \
    supervisor

#WERKT NIET??
#RUN cp -f /dsmr/dsmrreader/provisioning/django/settings.py.template /dsmr/dsmrreader/settings.py	
COPY ./dsmr/app/settings.py.template /dsmr/dsmrreader/settings.py	
	
RUN apk add --virtual .build-deps gcc python3-dev musl-dev postgresql-dev \
    && python3 -m pip install -r /dsmr/dsmrreader/provisioning/requirements/base.txt --no-cache-dir \
    && python3 -m pip install psycopg2 --no-cache-dir \
    && apk --purge del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*

RUN mkdir -p /run/nginx/ \
      && ln -sf /dev/stdout /var/log/nginx/access.log \
      && ln -sf /dev/stderr /var/log/nginx/error.log \
      && rm -f /etc/nginx/conf.d/default.conf \
      && mkdir -p /var/www/dsmrreader/static

COPY ./dsmr/app/supervisord.ini /etc/supervisor.d/supervisord.ini
COPY ./dsmr/app/run.sh /run.sh
RUN chmod u+x /run.sh

EXPOSE 80 443

WORKDIR /dsmr

CMD ["/bin/bash", "-c", "/run.sh"]
```

Any idea how to fix this?
