### ISSUE TITLE
DSMR webui start niet op na update

### ISSUE THREAD

**Issue by canedje** [xirixiz/dsmr-reader-docker#148]
Troubleshooting: https://dsmr-reader.readthedocs.io/nl/latest/troubleshooting.html#log-files

(Heb je DSMR-reader v4.4 of hoger? Zet dan hieronder ook de output van "dsmr_debuginfo") 

---
Vandaag DSMR docker geupdate.
Hierna start de docker wel op, maar de webui opend niet meer.
"Deze Site is niet bereikbaar"
Edit: na een tijdje wordt de docker ook gestopt.
Geen Log aanwezig om uit te lezen. ook geen dsmr_debug
Ik draai DSMR onder Unraid in een docker. Tot voor de update werkte het normaal.
Ik gebruik Postgres11 als DB
hoe kan ik terug naar de vorige versie?
setup:
![image](https://user-images.githubusercontent.com/23150947/97897611-063d0080-1d37-11eb-84ad-40d278993047.png)

**Comment by rogierlommers** [comment]
Ik denk dat je de nieuwe env vars moet gebruiken.

**Comment by xirixiz** [comment]
Klopt helemaal rogier, ik had het in de release erbij gezet maar dat valt denk ik niet genoeg op. Tevens zijn de SD_*_MQTT values al een tijd niet meer nodig en kunnen derhalve worden verwijderd. Thanks voor de bijdrage Rogier!

**Comment by canedje** [comment]
Klopt. Daar ben ik idd achter gekomen. Dank je
Ik heb de docker verwijderd en daarna opnieuw geïnstalleerd. De template is dan niet aangepast.

**Comment by xirixiz** [comment]
Die bestaat niet meer :). Zelf heb ik die vandaag ook pas verwijderd. In de toekomst zou dit beter vermeld moeten worden, ik zal kijken of ik daar al iets aan kan doen.

**Comment by canedje** [comment]
Thanks again

**Comment by dennissiemensma** [comment]
Weten jullie ook welke envvar het stuk maakt? 

Ik heb ze welliswaar al hernoemd in v4.5, maar ze zouden zeker **ook** nog via de oude naam beschikbaar moeten zijn (dat lijstje wat in de docs staat). Het was de bedoeling dat ze pas in v5.0 ook echt niet meer zouden werken.

**Comment by xirixiz** [comment]
Klopt Dennis, maar dat heeft met Docker te maken, ik heb de variabelen daar al uit verwijderd ✌🏻

**Comment by mchangsp** [comment]
Een tip: 
nadat ik de Postgres en DSMR Reader containers had verwijderd en environment variables had aangepast in mijn Docker Compose bestand, wilde DSMR Reader nog steeds niet starten. Ik had merkwaardige fouten in mijn log.
Toen heb ik de DSMR Reader container en image weggegooid, en een "docker-compose up -d" gedaan.
De DSMR Reader image en container werden opnieuw opgebouwd en toen werkte alles weer.

Hieronder zie je hoe mijn docker-compose.yml eruit ziet (vervang de userid en password door je eigen waardes)

```
version: '3'
services:
  db:
    image: postgres
    container_name: postgres-for-dsmr
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_DB=dsmrreader
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /etc/localtime:/etc/locatime:ro
      - /home/pi/projects/mydsmr/db:/var/lib/postgresql/data/pgdata
    ports:
      -  5432:5432
  dsmrreader:
      - POSTGRES_PASSWORD=dsmrreader
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /etc/localtime:/etc/locatime:ro
      - /home/pi/projects/mydsmr/db:/var/lib/postgresql/data/pgdata
    ports:
      -  5432:5432
  dsmrreader:
    image: xirixiz/dsmr-reader-docker
    cap_add:
      - NET_ADMIN
    container_name: dsmrreader
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DJANGO_DATABASE_HOST=a.b.c.d
      - DJANGO_DATABASE_USER=dsmrreader
      - DJANGO_DATABASE_PASSWORD=dsmrreader
#      - DB_HOST=a.b.c.d
#      - DSMR_USER=dsmrreader
#      - DSMR_PASSWORD=dsmrreader
#      - DSMR_EMAIL=root@localhost
    ports:
      - 7777:80
      - 7778:443
    devices:
      - "/dev/ttyUSB-P0:/dev/ttyUSB0"
    depends_on:
      - db

```
