### ISSUE TITLE
No matching manifest

### ISSUE THREAD

**Issue by Tralapo** [xirixiz/dsmr-reader-docker#183]
I can no longer update my DSMR-reader image, because there's no matching manifest found.

## Setup/Architecture information

- Raspberry Pi 3 Model B Rev 1.2
- Raspbian Buster
- Docker v20.10.5
- Docker-compose 1.27.4

## Configuration

```yaml
### DSMR Database en Reader ###
  dsmrdb:
    image: postgres:12-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/dsmr_backups:/dsmr/backups
      - ./data/dsmr_logs:/var/log/supervisor
    environment:
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DSMRREADER_LOGLEVEL=ERROR
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

## Describe the bug

Trying to update with `docker-compose pull` throws the following error message:

```
Pulling dsmr          ... pulling from xirixiz/dsmr-reader-...

ERROR: for dsmr  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
