### ISSUE TITLE
Missing ARM32v7 Image latest

### ISSUE THREAD

**Issue by MaartenMol** [xirixiz/dsmr-reader-docker#190]
I wanted to update to the newest release but notices that the latest tag doesn't provide a build for ARM32v7.

## Setup/Architecture information

Raspi 3b (ARM32v7)

## Version of the Docker image

REPOSITORY                   TAG                         IMAGE ID       CREATED       SIZE
xirixiz/dsmr-reader-docker   latest                      4d067c36461a   12 days ago   505MB
xirixiz/dsmr-reader-docker   latest-2021.03.02-arm32v7   4d067c36461a   12 days ago   505MB

## Configuration

```yaml

---
version: "3"
services:
  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/dsmr-backup:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - DJANGO_DATABASE_HOST=192.168.10.10
      - DJANGO_DATABASE_PORT=5433
      - DJANGO_DATABASE_USER=dsmrreader
      - DJANGO_DATABASE_PASSWORD=dsmrreader
    ports:
      - 7777:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

```

## Describe the bug
Newest build/image not available for ARM32v7. Older build does have AMR32v7.

## Debug log

```text

pi@raspberrypi:~/dsmr $ docker-compose pull
Pulling dsmr ... pulling from xirixiz/dsmr-reader-...

ERROR: for dsmr  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

```
