### ISSUE TITLE
onverwerkte telegrammen

### ISSUE THREAD

**Issue by ronniebee** [xirixiz/dsmr-reader-docker#192]
## Setup/Architecture information
  zotac mini pc (AMD), debian (buster)/ home assistant/docker/portainer/

## Version of the Docker image
the latest version,  Docker 20.10.5+azure on linux, am

## Configuration

```yaml
  dsmrdb:
    # When using Postgres, release 12.x is supported only
    # due to the limited availability of client packages, especially for arm32v7
    image: postgres:12
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:Add your docker(-compose) config file here.

```

## Describe the bug
Ben al uren bezig mijn reader weer aan de praat te krijgen. ik krijg in mijn home assistent het werkelijke stroomverbruik door maar als ik in dsmr reader kijk staan er > 10.000 onverwerkte telegrammen,

NB Heb de usb poort aangepast ( was veranderd van usb1 naar usb0)

kan je mij adviseren?

Nb ik ontvang dus wel real time data mbt mijn huidige stroonverbruik in HA ( mqtt werkt dus) maar probleem zit in de reader zelf denk ik...
Ik heb dus je docker compose gebruikt, daarna ingelogd  (xxx :7777) en kan het dsmr dashboard dus wel zien. 
Gisteren wel een andere mqtt stick in gebruik genomen en daarna begon het oplopen van de onverwerkte telegrammen. Causaal verband? Dat kan dus maar kan dit zelf niet verklaren.

UNRESOLVED ISSUES
Te veel onverwerkte telegrammen: 11703 19 uur geleden
Dagstatistieken lopen achter 1 dag, 14 uur geleden

## Debug log

```text

Add your logs here.

DSMR-READER
App / Python / Database v4.13 / v3.9.2 / postgresql
BE sleep / DL sleep / Retention / Override 5.0s / 5.0s / 672h / False
Latest telegram version read / Parser settings "50" / "4"

DATA
Telegrams total (est.) 25631
Consumption records electricity / gas (est.) 1396 / 280```
