### ISSUE TITLE
Day statistics are lagging behind 

### ISSUE THREAD

**Issue by KiefDelicious** [xirixiz/dsmr-reader-docker#223]
### Issue

Hi,

Ik heb sinds kort dat mijn archief niet meer bijgewerkt word, en kan niet achterhalen doe dat komt:

```
DSMR-READER
    App / Python / Database                                                      v4.19 / v3.10.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                       1.0s / 0.5s / -h / False
    Latest telegram version read / Parser settings                                                 "42" / "4"

DATA
    Telegrams total (est.)                                                                            4155907
    Consumption records electricity / gas (est.)                                               642816 / 12529

UNRESOLVED ISSUES
    Day statistics are lagging behind                                                    4 days, 12 hours ago

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                1123 MB
```

En kan eigenlijk niet vinden waar dat aan ligt. Ik heb DEBUG logging aan staan, zie bijlage (voor Portainer log), maar zie niks vreemds, kan ik op een of andere manier het proces niet forceren?. Ik draai op een synology DSM 6.2

Het zal vast iets stoms zijn, maar loop na lang zoeken toch echt vast. en gezien ik ook geen idee heb hoe ik deze commando's moet runnen: sudo supervisorctl restart dsmr_backend, zou een duwtje in de juiste richting helpen :)

**EDIT**
Ik zie nu dat mijn gas meter sinds donderdag zo te zien niks meer doorgeeft. Ik zie wel live data van elektra, maar niet van gas, zou dat er mee te maken hebben?

### Which version has the issue?

xirixiz/dsmr-reader-docker:latest

### What was the last working version?

xirixiz/dsmr-reader-docker:latest

### What type of installation are you running (architecture)?

Other

### Anything in the logs that might be useful?

[_dsmr_logs.txt](https://github.com/xirixiz/dsmr-reader-docker/files/7533611/_dsmr_logs.txt)

### Additional information

Docker Compose

```
version: '3.2'
services:
  dsmrdb:
    # When using Postgres, release 12.x is supported only
    # due to the limited availability of client packages, especially for arm32v7
    image: postgres:12.4-alpine
    container_name: dsmr_db
    restart: always
    volumes:
      - /volume1/docker/dsmr/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=*********
      - POSTGRES_DB=dsmrreader
    networks:
      - local-energy
  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /volume1/docker/dsmr/backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DSMRREADER_ADMIN_PASSWORD=*********
      - DSMRREADER_LOGLEVEL=DEBUG
    networks:
      - local-energy
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
networks:
  local-energy:
   name: local-energy
```
