### ISSUE TITLE
The dsmr_webinterface won't start after upgrading to latest image

### ISSUE THREAD

**Issue by sbosman84** [xirixiz/dsmr-reader-docker#244]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

After recreating the container based on the latest image (created at 2021-12-21 22:41:09). It won't start the webinterface part.

The latest output of the container keeps on repeating:
curl: option --connect-timeout 15 --silent --show-error --fail: is unknown curl: try 'curl --help' or 'curl --manual' for more information

After running the reload.sh script inside the container it shows that the dsmr_webinterface is not running as well:
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/15688831/147295167-6f747e9b-6c41-4790-8869-895341ca5261.png">

### Expected behaviour

The container used to start normal before. But after the upgrade it doesn't start the web interface.

### Actual behaviour

After the upgrade to the latest image version to start as normal

### Steps to reproduce

1. Upgrade the container image to Docker 20.10.11+azure-3 on linux, arm64
2. Recreate the container
3. Restart the container

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 26
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1047-raspi
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.627GiB
 Name: 
 ID: BZRU:HNDP:K2DY:7GN4:FWWI:NS4G:FG36:ZAWK:XGKW:E7CM:YWO3:B2XH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

### Version

* Docker compose version (type `docker-compose --version`):
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

* System info (type `uname -a`):
`Linux thor 5.4.0-1047-raspi #52-Ubuntu SMP PREEMPT Wed Nov 24 08:16:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

### Docker compose

```yaml
dsmr:
    container_name: dsmr
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATALOGGER_MODE: receiver
      DJANGO_DATABASE_HOST: *
      DJANGO_DATABASE_NAME: *
      DJANGO_DATABASE_PASSWORD: *
      DJANGO_DATABASE_USER: *
      DJANGO_SECRET_KEY: *
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DSMRREADER_ADMIN_PASSWORD: *
      DSMRREADER_ADMIN_USER: admin
      DSMRREADER_LOGLEVEL: WARNING
      ENABLE_NGINX_SSL: "false"
      SD_AUTORESTART_DATALOGGER: "false"
      SD_AUTOSTART_DATALOGGER: "false"
      VIRTUAL_HOST: localhost
    image: xirixiz/dsmr-reader-docker:latest  
    links:
    - postgres
    networks:
      web: null
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/docker-data/dsmr/backups:/dsmr/backups:rw
```

### Container logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-set-app-defaults: executing... 

[ INFO ] DSMR release: 4.19.0

[ INFO ] Creating log directory...

[ INFO ] Setting architecture requirements...

[ INFO ] ARM Architecture

[ INFO ] Verifying if the DSMR web credential variables have been set...

[ INFO ] Verifying database connectivity to host: postgres with port: 5432...

[ INFO ] Database connectivity successfully verified!

[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.
563 static files copied to '/var/www/dsmrreader/static'.
Updating password of superuser "admin"
Deactivating any other existing superusers

[ INFO ] Checking for NGINX SSL configuration...

[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...

[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...

[ INFO ] Configuring DSMR in receiver datalogger mode....
[cont-init.d] 10-set-app-defaults: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - nginx...
[services.d] done.
[2021-12-23 18:30:23 +0100] [240] [INFO] Starting gunicorn 20.1.0
[2021-12-23 18:30:23 +0100] [240] [INFO] Listening at: unix:/var/tmp/gunicorn--dsmr_webinterface.socket (240)
[2021-12-23 18:30:23 +0100] [240] [INFO] Using worker: sync
[2021-12-23 18:30:23 +0100] [268] [INFO] Booting worker with pid: 268
