### ISSUE TITLE
Webinterface not available (docker container keeps restarting)

### ISSUE THREAD

**Issue by pietervanharen** [xirixiz/dsmr-reader-docker#247]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since I added a volume to save backups on my host machine the webinterface of dsmr-reader is no longer loading. In the logs of the container I see the same lines constantly reappearing.

### Expected behaviour

Webinterface is available
MQTT messages are being received by the broker

### Actual behaviour

Webinterface is not available
No MQTT messages are being received by the broker

### Steps to reproduce

1. Start the database container (postgres:latest)
2. Start the dsmr container (xirixiz/dsmr-reader-docker:latest)
3. Access the webinterface using a browser

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 21
  Running: 19
  Paused: 0
  Stopped: 2
 Images: 26
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-50-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: ubuntu-desktop
 ID: H2Z6:4M4U:6T7D:W2LC:XFGK:7DFV:KERP:K3DC:DZ4P:PPPF:OMF4:HKHM
 Docker Root Dir: /media/pieter/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

### Version

* Docker compose version: 1.26.0, build d4451659
* System info (type `uname -a`): Linux ubuntu-desktop 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
using Portainer (docker noob)
```

### Container logs

0 static files copied to '/var/www/dsmrreader/static', 563 unmodified.
Updating password of superuser "admin
Deactivating any other existing superusers
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[cont-init.d] 10-set-app-defaults: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting DSMR Reader - datalogger...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - nginx...
[services.d] done.
ifelse: fatal: unable to exec /app/run.sh: No such file or directory
[cmd] /app/run.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-set-app-defaults: executing... 
[ INFO ] DSMR release: 4.19.0
[ INFO ] Creating log directory...
[ INFO ] Setting architecture requirements...
[ INFO ] X64 Architecture
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: 192.168.1.19 with port: 49153...
[ INFO ] Database connectivity successfully verified!
[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.
0 static files copied to '/var/www/dsmrreader/static', 563 unmodified.
Updating password of superuser "admin"
Deactivating any other existing superusers
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[cont-init.d] 10-set-app-defaults: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting DSMR Reader - webinterface...
Starting DSMR Reader - nginx...
Starting DSMR Reader - datalogger...
[services.d] done.
ifelse: fatal: unable to exec /app/run.sh: No such file or directory
[cmd] /app/run.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.

### Additional info

I moved from a local dsmr-reader running on a Raspberry Pi to a docker container using esp-link on a SlimmeLezer. The container wasn't able to save backups, that's why I wanted to add the volume
