### ISSUE TITLE
Latest dsmr-docker versions prevents transfer of data

### ISSUE THREAD

**Issue by poerlemans** [xirixiz/dsmr-reader-docker#251]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After installations of the latest dsmr-docker version (amd64-2021.12.09 or latest the transfer of data to dsmr is blocked. After installation of the older version (amd64-2021.12.08) transfer starts again.

### Expected behaviour

Logging of data.

Log in portainer:
127.0.0.1 - - [06/Jan/2022:09:09:44 +0100] "GET /about HTTP/1.1" 200 14963 "-" "curl/7.79.1" "-"

      
      
    

### Actual behaviour

Non logging of data

Log in Portainer:
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
2022-01-06 08:48:56,747 ERROR    mixins       run_once                        103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 34, in read_telegram
    serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
  File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0: [Errno 13] Permission denied: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/dsmr_backend/mixins.py", line 92, in run_once
    self.run(data=self.data, **options)
  File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
    telegram = next(self.telegram_generator)
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 36, in read_telegram
    raise RuntimeError('Failed to connect: {}', error)
RuntimeError: ('Failed to connect: {}', SerialException(13, "could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0: [Errno 13] Permission denied: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0'"))
127.0.0.1 - - [06/Jan/2022:08:48:57 +0100] "GET /about HTTP/1.1" 200 15552 "-" "curl/7.79.1" "-"
Starting DSMR Reader - datalogger...

### Steps to reproduce

See above

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                                                                                                                                                                                                             yslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-92-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 2.918GiB
 Name: ubuntuvirtualmachine
 ID: GD3N:J552:THNC:FZQV:WCO7:SLHR:DUM3:VCIK:PGOB:EPPG:T4AF:AHXV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```


### Version

* Docker compose version (type `docker-compose --version`): version 1.27.4, build 40524192
* System info (type `uname -a`): Linux ubuntuvirtualmachine 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


### Docker compose

```yaml
services:
  chronograf:
    container_name: chronograf
    environment:
      PGID: '998'
      PUID: '1000'
      TZ: Europe/Amsterdam
    image: chronograf:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
    - influxdb
    ports:
    - published: 8888
      target: 8888
    restart: always
    volumes:
    - /home/peter/docker/chronograf/data:/var/lib/chronograf:rw
  dsmr:
    cap_add:
    - NET_ADMIN
    container_name: dsmr
    depends_on:
      dsmrdb:
        condition: service_started
    devices:
    - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH2F1L70-if00-port0
    environment:
      DJANGO_DATABASE_HOST: dsmrdb
      DJANGO_DATABASE_NAME: dsmrreader
      DJANGO_DATABASE_PASSWORD: xxxx
      DJANGO_DATABASE_PORT: '5432'
      DJANGO_DATABASE_USER: dsmrreader
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DSMR_EMAIL: root@localhost
      DSMR_PASSWORD: xxxx
      DSMR_USER: admin
      ENABLE_IFRAME: "true"
      SD_GROUP: root
      SD_LOGLEVEL: info
      SD_USER: root
      VIRTUAL_HOST: localhost
    image: xirixiz/dsmr-reader-docker:amd64-2021.12.08
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
    - dsmrdb
    ports:
    - published: 7777
      target: 80
    - published: 7779
      target: 443
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/peter/docker/dsmr_backups:/dsmr/backups:rw
  dsmrdb:
    container_name: dsmrdb
    environment:
      PG_TZ: Europe/Amsterdam
      POSTGRES_DB: dsmrreader
      POSTGRES_PASSWORD: xxxx
      POSTGRES_USER: dsmrreader
      TZ: Europe/Amsterdam
    image: postgres:13-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
    - /home/peter/docker/dsmrdb:/var/lib/postgresql/data:rw
    - /etc/localtime:/etc/localtime:ro
  influxdb:
    container_name: influxdb
    environment:
      INFLUXDB_PASSWORD: xxxx
      INFLUXDB_USER: admin
      PGID: '998'
      PUID: '1000'
      TZ: Europe/Amsterdam
    image: influxdb:1.8
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
    - published: 8086
      target: 8086
    restart: always
    volumes:
    - /home/peter/docker/influxdb/data:/var/lib/influxdb:rw
  portainer:
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    environment:
      TZ: Europe/Amsterdam
    hostname: portainer
    image: portainer/portainer-ce
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
    - published: 9000
      target: 9000
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /home/peter/docker/portainer/data:/data:rw
    - /home/peter/docker/shared:/shared:rw
  s0pcm:
    container_name: s0pcm
    devices:
    - /dev/serial/by-id/usb-Arduino_LLC_Arduino_Leonardo-if00:/dev/serial/by-id/usb-Arduino_LLC_Arduino_Leonardo-if00
    image: ualex73/s0pcm-reader:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/peter/docker/s0pcm:/config:rw
    - /dev:/dev:rw
  swag:
    cap_add:
    - NET_ADMIN
    container_name: swag
    environment:
      DUCKDNSTOKEN: xxxxxx
      EMAIL: pjm.oerlemans@gmail.com
      MAXMINDDB_LICENSE_KEY: xxxxxxxx
      PGID: '998'
      PUID: '1000'
      SUBDOMAINS: wildcard
      TZ: Europe/Amsterdam
      URL: xxxxxxx.duckdns.org
      VALIDATION: duckdns
    image: linuxserver/swag
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/peter/docker/swag/config:/config:rw
  tasmocompiler:
    container_name: tasmocompiler
    environment:
      DEBUG: server,git,compile
      PGID: '998'
      PUID: '1000'
      TZ: Europe/Amsterdam
    image: benzino77/tasmocompiler
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
    - published: 3000
      target: 3000
    restart: always
    volumes:
    - /home/peter/docker/tasmocompiler:/tmp:rw
  watchtower:
    command: --schedule "0 0 4 * * *" --cleanup --label-enable
    container_name: watchtower
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.6'
```


### Container logs

See above

### Additional info

_No response_
