### ISSUE TITLE
Container state "unhealthy" "Output":"/bin/sh: /app/healthcheck.sh: not found

### ISSUE THREAD

**Issue by davidvf** [xirixiz/dsmr-reader-docker#259]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Using the latest version of the dsmr container, i noticed the container state is unhealthy.

### Expected behaviour

Should be healthy

### Actual behaviour

```
[david@hawk:~ $] docker inspect --format='{{json .State.Health}}' dsmr | jq
{
   "Status":"unhealthy",
   "FailingStreak":5331,
   "Log":[
      {
         "Start":"2022-01-11T10:40:15.94304312+01:00",
         "End":"2022-01-11T10:40:16.181417326+01:00",
         "ExitCode":1,
         "Output":"/bin/sh: /app/healthcheck.sh: not found\n"
      },
      {
         "Start":"2022-01-11T10:40:26.203989088+01:00",
         "End":"2022-01-11T10:40:26.369851284+01:00",
         "ExitCode":1,
         "Output":"/bin/sh: /app/healthcheck.sh: not found\n"
      },
      {
         "Start":"2022-01-11T10:40:36.391198988+01:00",
         "End":"2022-01-11T10:40:36.613236128+01:00",
         "ExitCode":1,
         "Output":"/bin/sh: /app/healthcheck.sh: not found\n"
      },
      {
         "Start":"2022-01-11T10:40:46.647506854+01:00",
         "End":"2022-01-11T10:40:46.835680289+01:00",
         "ExitCode":1,
         "Output":"/bin/sh: /app/healthcheck.sh: not found\n"
      },
      {
         "Start":"2022-01-11T10:40:56.858819843+01:00",
         "End":"2022-01-11T10:40:57.079804438+01:00",
         "ExitCode":1,
         "Output":"/bin/sh: /app/healthcheck.sh: not found\n"
      }
   ]
}
```

### Steps to reproduce

```
[david@hawk:~ $] docker exec -ti dsmr /bin/sh
root@dsmr_reader_docker:/app# which ls
/bin/ls
root@dsmr_reader_docker:/app# ls -alh
total 376K
drwxr-xr-x 1 app  app  4.0K Jan 10 06:59 .
drwxr-xr-x 1 root root 4.0K Jan 10 11:01 ..
-rw-r--r-- 1 app  app   415 Oct 23 16:12 .codecov.yml
-rw-r--r-- 1 app  app   270 Oct 23 16:12 .coveragerc
-rw-r--r-- 1 app  app  1.3K Oct 23 16:12 .env.template
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 .github
-rw-r--r-- 1 app  app   455 Oct 23 16:12 .gitignore
-rw-r--r-- 1 app  app     0 Jan 10 06:59 .gitkeep
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 .idea
-rw-r--r-- 1 app  app   430 Oct 23 16:12 .readthedocs.yml
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 .settings
-rw-r--r-- 1 app  app   14K Oct 23 16:12 LICENSE.md
-rw-r--r-- 1 app  app  2.4K Oct 23 16:12 README.md
-rw-r--r-- 1 app  app   314 Oct 23 16:12 RELEASE
drwxr-xr-x 1 app  app  4.0K Jan 11 01:00 backups
lrwxrwxrwx 1 app  app    28 Oct 23 16:12 changelog.rst -> docs/reference/changelog.rst
-rwxr-xr-x 1 app  app   787 Oct 23 16:12 check_python_version.py
-rwxr-xr-x 1 app  app   652 Jan 10 06:59 cleandb.sh
-rwxr-xr-x 1 app  app  1.3K Oct 23 16:12 deploy.sh
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 docs
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_api
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_backend
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_backup
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_consumption
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_datalogger
-rw-r--r-- 1 app  app  6.4K Jan 10 06:59 dsmr_datalogger_api_client.py
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_dropbox
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_frontend
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_influxdb
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_mindergas
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_mqtt
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_notification
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_parser
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_plugins
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_pvoutput
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_stats
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmr_weather
drwxr-xr-x 1 app  app  4.0K Jan 10 11:02 dsmrreader
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 logs
-rwxr-xr-x 1 app  app   254 Oct 23 16:12 manage.py
-rw-r--r-- 1 app  app   79K Oct 23 16:12 poetry.lock
-rwxr-xr-x 1 app  app  2.1K Oct 23 16:12 post-deploy.sh
-rwxr-xr-x 1 app  app   322 Oct 23 16:12 pre-deploy.sh
-rw-r--r-- 1 app  app   156 Oct 23 16:12 pylama.ini
-rw-r--r-- 1 app  app  1.4K Oct 23 16:12 pyproject.toml
-rwxr-xr-x 1 app  app  1.2K Oct 23 16:12 reload.sh
-rw-r--r-- 1 app  app   110 Oct 23 16:12 setup.cfg
drwxr-xr-x 1 app  app  4.0K Oct 23 16:12 tools
root@dsmr_reader_docker:/app#
```

### Docker info

```yaml
[david@hawk:~ $] docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.63-v7+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: hawk.home
 ID: QD75:LW7N:SMLC:BZ73:IFYM:YBQ2:GAI5:ZUAC:JFNA:YQ7X:MENG:HD2F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: No memory limit support
WARNING: No swap limit support

[david@hawk:~ $]
```
```


### Version

* Docker compose version (type `docker-compose --version`):
`[david@hawk:~ $] docker-compose --version
docker-compose version 1.25.0, build unknown
`

* System info (type `uname -a`):
`
Linux hawk.home 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux
`


### Docker compose

```yaml
docker run -d --name="dsmr" --restart always -p 7777:80 -p 7779:443 -e DJANGO_DATABASE_HOST='192.168.2.10' -e DJANGO_DATABASE_NAME=dsmrreader -e DJANGO_DATABASE_USER=dsmrreader -e DJANGO_DATABASE_PASSWORD=xxxxx -e DJANGO_DATABASE_PORT=5432 -e VIRTUAL_HOST='hawk.home' -e DSMRREADER_ADMIN_USER=admin -e DSMR_EMAIL=root@localhost -e DSMRREADER_ADMIN_PASSWORD=xxxx --device /dev/ttyUSB0:/dev/ttyUSB0 xirixiz/dsmr-reader-docker:latest
```
```


### Container logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------
User UID: 803
User GID: 803
-------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing...
[ INFO ] DSMR Reader release: 4.19.0
[ INFO ] DSMR Reader Docker release: 2022.01.03
[ INFO ] Ensure permissions...
[ INFO ] Setting architecture requirements...
[ INFO ] ARM Architecture
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: 192.168.2.10 with port: 5432...
[ INFO ] Database connectivity successfully verified!
[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.

0 static files copied to '/var/www/dsmrreader/static', 563 unmodified.
Updating password of superuser "admin"
Deactivating any other existing superusers
[ INFO ] Checking for NGINX SSL configuration...
[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[cont-init.d] 20-set-app-defaults: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting DSMR Reader - nginx...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - datalogger...
[services.d] done.
[2022-01-10 18:09:35 +0000] [282] [INFO] Starting gunicorn 20.1.0
[2022-01-10 18:09:35 +0000] [282] [INFO] Listening at: unix:/var/tmp/gunicorn--dsmr_webinterface.socket (282)
[2022-01-10 18:09:35 +0000] [282] [INFO] Using worker: sync
[2022-01-10 18:09:35 +0000] [310] [INFO] Booting worker with pid: 310
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
```

### Additional info

_No response_
