### ISSUE TITLE
High CPU usage and permission errors on Home Assistant OS 

### ISSUE THREAD

**Issue by sanderdw** [xirixiz/dsmr-reader-docker#262]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Unfortunately i was a bit optimistic (https://github.com/xirixiz/dsmr-reader-docker/issues/251#issuecomment-1012003566) and the new version is causing some weird cpu usage: https://github.com/sanderdw/hassio-addons/issues/28

Also the mount option which worked correctly is causing permission problems now (map option in https://developers.home-assistant.io/docs/add-ons/configuration).

### Expected behaviour

No high cpu usage and be able to write back to hassio folders

### Actual behaviour

See description

### Steps to reproduce

-

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 60
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
 Kernel Version: 5.10.88
 Operating System: Home Assistant OS 7.1
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 3.728GiB
 Name: homeassistant
 ID: TDYM:NYBM:6NEK:EOZI:ZP57:GQGR:VHY5:JYNB:MXTZ:BLGH:4QGM:3LN3
 Docker Root Dir: /mnt/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

### Docker compose

```yaml
-
```

### Container logs

https://github.com/sanderdw/hassio-addons/issues/28

<img width="796" alt="image" src="https://user-images.githubusercontent.com/19476345/149959422-6a2306ca-b0f5-4b3c-a062-9fcbfe8557e8.png">
