### ISSUE TITLE
Backup does not work

### ISSUE THREAD

**Issue by jimmyd-be** [xirixiz/dsmr-reader-docker#277]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

When I configure daily backup to be made the backup is not triggered to be made.

### Expected behaviour

That DSMR reader create a daily backup on a specific time.

### Actual behaviour

After configuring the daily backup, nothing happens on the backup timestamp.

### Steps to reproduce

1. Configure daily backup
2. See logs and see that it does not work

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.103-v7+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: pi-digitale-meter
 ID: UXJQ:RZ7C:67KV:UOH4:QFCN:AXP2:JLLO:NCMS:J25M:66BW:TKXN:ZNG4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Version

docker-compose version 1.29.2, build unknown
Linux pi-digitale-meter 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

### Docker compose

```yaml
version: '3.8'

services:
  dsmrdb:
    # When using Postgres, release 12.x is supported only
    # due to the limited availability of client packages, especially for arm32v7
    image: postgres:13-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /home/pi/config/postgres_dsmr:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Brussels
      - PG_TZ=Europe/Brussels
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      dsmrdb:
        condition: service_healthy
    container_name: dsmr
    links:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/backup/dsmr_backups:/app/backups
    environment:
      - TZ=Europe/Brussels
      - DJANGO_TIME_ZONE=Europe/Brussels
      - VIRTUAL_HOST=localhost
    ports:
      - "7777:80"
      - "7779:443"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-Lsf",
          "http://127.0.0.1/about",
          "-o",
          "/dev/null",
          "-w",
          "HTTP_%{http_code}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

#volumes:
#  dsmrdb:
#  dsmrdb_backups:
```

### Container logs

Nothing in the logs. Expect 
127.0.0.1 - - [27/Mar/2022:08:09:41 +0200] "GET /about HTTP/1.1" 200 15455 "-" "curl/7.79.1" "-"
