### ISSUE TITLE
Log flooded with 127.0.0.1 - - [04/Aug/2022:13:36:37 +0200] "GET /about HTTP/1.1" 200 16141 "-" "curl/7.83.1" "-"

### ISSUE THREAD

**Issue by JeeKee80** [xirixiz/dsmr-reader-docker#294]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

log flooded with 127.0.0.1 - - [04/Aug/2022:13:36:37 +0200] "GET /about HTTP/1.1" 200 16141 "-" "curl/7.83.1" "-"

### Expected behaviour

log not getting flooded

### Actual behaviour

log getting flooded with 127.0.0.1 - - [04/Aug/2022:13:36:37 +0200] "GET /about HTTP/1.1" 200 16141 "-" "curl/7.83.1" "-"

### Steps to reproduce

Untouched docker install

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.32-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 Name: raspberrypi
 ID: EPHP:J67I:D53Y:SKGR:FZPL:42GE:GAPB:KGOP:VUBM:BMP5:CTRN:AA55
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Version

Docker Compose version v2.6.0
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

### Docker compose

```yaml
NA
```

### Container logs

[_dsmr_logs.txt](https://github.com/xirixiz/dsmr-reader-docker/files/9259431/_dsmr_logs.txt)
