### ISSUE TITLE
dsmr docker 2.5GB when exporting

### ISSUE THREAD

**Issue by hemant5400z** [xirixiz/dsmr-reader-docker#295]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

Im moving my docker to another server hence exporting both dsmr and dsmrdb. I noticed that dsmr docker is almost 2.5 GB. Expected the dsmrdb to be large as it contians the database but is uses the volume mapping to store the DB.

What I don't understand why the dsmr docker is that large as it does not contain any data only the configs. I also deleted the backupdir contents to be sure the issues was not there but still the dsmr docker is 2.5 GB not sure what it storing there.

Can someone help me to understand /cleanup this docker?

### Expected behaviour

dsmr should be small similar approx 300-400 MB.

### Actual behaviour

The dsmr docker has grown to a huge beast 2.5 GB when exporting.

### Steps to reproduce

Export docker from Synology docker panel.

### Docker info

```yaml
Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 17
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b1dc45ec561bd867c4805eee786caab7cc83acae
 runc version: 89783e1862a2cc04647ab15b6e88a0af3d66fac3
 init version: 12b6a20 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 3.10.105
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.961GiB
 Name: HAGPAZ1-S-05
 ID: WYNU:4ZHT:AUDS:DN5A:G7N6:NVZS:TJCN:4NUF:GKWI:MU73:4AYY:THNS
 Docker Root Dir: /volume1/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
* docker-compose version 1.28.5, build 1bbbad71

* System info (type `uname -a`):
Linux  3.10.105 #25426 SMP Tue May 12 04:40:16 CST 2020 x86_64 GNU/Linux synology_bromolow_3615xs

### Docker compose

```yaml
not sure if this is relevant
```

### Container logs

not sure if this is relevant
