### ISSUE TITLE
ENV for Remote datalogger is not used

### ISSUE THREAD

**Issue by Ankh-** [xirixiz/dsmr-reader-docker#303]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Got a new docker installation running with the following snippet:
```
      - DSMRREADER_REMOTE_DATALOGGER_MODE=standalone
      - DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD=ipv4
      - DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST=192.168.30.10
      - DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT=23
```
I've got a P1 E20 ethernet (Zuidwijk) running nicely. When checking telnet for data, there is actual data. So something is wrong regarding the docker compose ENV.  

### Expected behaviour

Actual data!

### Actual behaviour

Errors :(

> dsmr    | 2022-12-07 20:38:06,236 ERROR    mixins       run_once                        107 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
dsmr    |   File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 322, in open
dsmr    |     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
dsmr    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dsmr    | FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'
dsmr    |
dsmr    | During handling of the above exception, another exception occurred:
dsmr    |
dsmr    | Traceback (most recent call last):
dsmr    |   File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 39, in read_telegram
dsmr    |     serial_handle = serial.serial_for_url(
dsmr    |                     ^^^^^^^^^^^^^^^^^^^^^^
dsmr    |   File "/usr/local/lib/python3.11/site-packages/serial/__init__.py", line 90, in serial_for_url
dsmr    |     instance.open()
dsmr    |   File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 325, in open
dsmr    |     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
dsmr    | serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
dsmr    |
dsmr    | The above exception was the direct cause of the following exception:
dsmr    |
dsmr    | Traceback (most recent call last):
dsmr    |   File "/app/dsmr_backend/mixins.py", line 96, in run_once
dsmr    |     self.run(data=self.data, **options)
dsmr    |   File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
dsmr    |     telegram = next(self.telegram_generator)
dsmr    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dsmr    |   File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 43, in read_telegram
dsmr    |     raise RuntimeError("Failed to connect: {}", error) from error
dsmr    | RuntimeError: ('Failed to connect: {}', SerialException(2, "could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'"))
dsmr    |

### Steps to reproduce

basic yaml with added remote datalogger

### Docker info

```yaml
root@box:/docker/dsmr# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.13.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.44GiB
 Name: box
 ID: BISR:P377:UHHH:HYO6:4JHT:XYT2:4JGN:XXEQ:OAKF:7WUK:VJ3T:XZAK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

see docker info

### Docker compose

```yaml
root@box:/docker/dsmr# docker compose config
name: dsmr
services:
  dsmr:
    cap_add:
    - NET_ADMIN
    container_name: dsmr
    depends_on:
      dsmrdb:
        condition: service_healthy
    environment:
      DGID: "1000"
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD: ipv4
      DSMRREADER_REMOTE_DATALOGGER_MODE: standalone
      DSMRREADER_REMOTE_DATALOGGER_NETWORK_HOST: 192.168.30.10
      DSMRREADER_REMOTE_DATALOGGER_NETWORK_PORT: "23"
      DUID: "1000"
      TZ: Europe/Amsterdam
      VIRTUAL_HOST: localhost
    healthcheck:
      test:
      - CMD
      - curl
      - -Lsf
      - http://127.0.0.1/about
      - -o
      - /dev/null
      - -w
      - HTTP_%{http_code}
      timeout: 5s
      interval: 10s
      retries: 10
    image: xirixiz/dsmr-reader-docker:latest
    links:
    - dsmrdb
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "7777"
      protocol: tcp
    - mode: ingress
      target: 443
      published: "7779"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /docker/dsmr/dsmr_backups
      target: /app/backups
      bind:
        create_host_path: true
  dsmrdb:
    container_name: dsmrdb
    environment:
      DGID: "1000"
      DUID: "1000"
      PG_TZ: Europe/Amsterdam
      POSTGRES_DB: dsmrreader
      POSTGRES_PASSWORD: dsmrreader
      POSTGRES_USER: dsmrreader
      TZ: Europe/Amsterdam
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U dsmrreader
      timeout: 5s
      interval: 10s
      retries: 10
    image: postgres:14-alpine
    networks:
      default: null
    restart: always
    volumes:
    - type: bind
      source: /docker/dsmr/dsmrdb
      target: /var/lib/postgresql/data
      bind:
        create_host_path: true
networks:
  default:
    name: dsmr_default
root@box:/docker/dsmr#
```

### Container logs

see errors
