### ISSUE TITLE
Geen buienradar data

### ISSUE THREAD

**Issue by eyepeople1969** [xirixiz/dsmr-reader-docker#306]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

[dsmr buienradar.pdf](https://github.com/xirixiz/dsmr-reader-docker/files/10200154/dsmr.buienradar.pdf)

Beste Bram, 

Ik heb een issue met het laden van de data van buienradar.

Ik zie op mijn firewall dat er continue een client-rst voorkomt (zie ook pdf met screenshot 1e plaatje)
als ik een curl https://data/buienradar.nl doe dan zie je in de packetcapture (2e plaatje) dat deze goed gaat
maar vanuit de dsmr gezien (3e plaatje) zie je dat het fout gaat.

Ik heb de DSMRREADER_REMOTE_DATALOGGER_DEBUG_LOGGING=true en DSMRREADER_LOGLEVEL=DEBUG gezet in de environment settings maar in /var/log zie ik niets aan logging.

Nu is mijn linux/docker kennis beperkt maar ik vraag mij af wat verkeerd doe en hoe kan ik de debug log aan krijgen?

Verder is het mogelijk een bekend iets.

Alvast hartelijk dank voor het kijken.

George van Kampen

### Expected behaviour

Expected was dat er een grafiek te zien was.

### Actual behaviour

Geen grafiek te zien

### Steps to reproduce

Hij kan geen connectie maken met data.buienrada.nl dus is het altijd te reproduceren.

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.17-meson64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.696GiB
 Name: DietPi
 ID: KJ32:LHB2:EDVI:GH4T:COR3:XC6P:KFOO:3FR6:TF4W:2MKF:KCYN:GKUW
 Docker Root Dir: /mnt/dietpi_userdata/docker-data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  registry.cube.local:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

Docker Compose version v2.13.0

Linux DietPi 5.19.17-meson64 #22.11.1 SMP PREEMPT Wed Nov 30 11:05:42 UTC 2022 aarch64 GNU/Linux

### Docker compose

```yaml
name: docker
services:
  dsmr:
    cap_add:
    - NET_ADMIN
    container_name: dsmr
    depends_on:
      dsmrdb:
        condition: service_healthy
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DSMRREADER_LOGLEVEL: DEBUG
      DSMRREADER_REMOTE_DATALOGGER_DEBUG_LOGGING: "true"
      TZ: Europe/Amsterdam
      VIRTUAL_HOST: localhost
    healthcheck:
      test:
      - CMD
      - curl
      - -Lsf
      - http://127.0.0.1/about
      - -o
      - /dev/null
      - -w
      - HTTP_%{http_code}
      timeout: 5s
      interval: 10s
      retries: 10
    image: xirixiz/dsmr-reader-docker:latest
    links:
    - dsmrdb
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: "7777"
      protocol: tcp
    - mode: ingress
      target: 443
      published: "7779"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /home/dietpi/docker/dsmr_backups
      target: /app/backups
      bind:
        create_host_path: true
  dsmrdb:
    container_name: dsmrdb
    environment:
      PG_TZ: Europe/Amsterdam
      POSTGRES_DB: dsmrreader
      POSTGRES_PASSWORD: dsmrreader
      POSTGRES_USER: dsmrreader
      TZ: Europe/Amsterdam
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      timeout: 5s
      interval: 10s
      retries: 10
    image: postgres:13-alpine
    networks:
      default: null
    restart: always
    volumes:
    - type: bind
      source: /home/dietpi/docker/dsmrdb
      target: /var/lib/postgresql/data
      bind:
        create_host_path: true
networks:
  default:
    name: docker_default
```

### Container logs

Die zijn er dus niet..

### Additional info

Geen
