### ISSUE TITLE
Container can only start if serial device is on ttyUSB*

### ISSUE THREAD

**Issue by golles** [xirixiz/dsmr-reader-docker#310]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since the latest release, the serial port needs to be on a `ttyUSB*` port, commit: de0cec303a71445efe505f9b2549b90db0cf97a1

Getting this error: https://github.com/xirixiz/dsmr-reader-docker/blob/master/rootfs/etc/cont-init.d/20-set-app-defaults#L84

### Expected behaviour

The container deals with serial devices on other locations than ttyUSB

### Actual behaviour

The container can only start when I set the serial device on a ttyUSB*

### Steps to reproduce

See docker-compose below

### Docker info

```yaml
NA.
```

### Version

* Docker compose version (type `docker-compose --version`): docker-compose version 1.29.2, build unknown
* System info (type `uname -a`): Linux nuc10i3fnh 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
dsmr:
    container_name: dsmr
    image: xirixiz/dsmr-reader-docker:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DJANGO_TIME_ZONE=${TZ}
      - VIRTUAL_HOST=localhost
      - DSMRREADER_ADMIN_USER=${DSMRREADER_ADMIN_USER}
      - DSMRREADER_ADMIN_PASSWORD=${DSMRREADER_ADMIN_PASSWORD}
      - DJANGO_DATABASE_HOST=${DJANGO_DATABASE_HOST}
    ports:
      - 7777:80
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AQ4KS8IA-if00-port0:/dev/dsmr
```

### Container logs

Haven't stored any logs
