### ISSUE TITLE
DSMRREADER_OPERATION_MODE=api_client not working

### ISSUE THREAD

**Issue by puijken** [xirixiz/dsmr-reader-docker#311]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When starting the container with api_client paramater as a remote datalogger, it tries to make a connection to the database which it should not do.

### Expected behaviour

Start container, do not try to connect to database but just send the P1 telegrams to the api_server.

### Actual behaviour

Upon starting it tries to connect to the dabase and keeps retrying, see logs.

### Steps to reproduce

Create the remote datalogger container with enviroment variable:

- DSMRREADER_OPERATION_MODE=api_client

### Docker info

```yaml
N/A - syntax change in dsmrreader does not seem to work in docker container anymore
```

### Version

N/A - syntax change in dsmrreader does not seem to work in docker container anymore

### Docker compose

```yaml
version: '3'
services:
  dsmr_remote:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr_remote
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - DSMRREADER_REMOTE_DATALOGGER_API_KEYS=**redacted**
      - DSMRREADER_REMOTE_DATALOGGER_API_HOSTS=**redacted**
      - DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD=serial
      - DSMRREADER_OPERATION_MODE=api_client
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_PORT=/dev/ttyUSB0
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_BAUDRATE=115200
      - DSMRREADER_REMOTE_DATALOGGER_SLEEP=5
      - DSMRREADER_REMOTE_DATALOGGER_DEBUG_LOGGING=false
      - DSMRREADER_LOGLEVEL=WARNING
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    healthcheck:
      disable: true
    labels:
      com.docker.compose.project: dsmr_remote
      com.docker.compose.service: dsmr_remote
    networks:
      macvlan12:
        ipv4_address: 10.0.12.202
networks:
  macvlan12:
    external: true
```

### Container logs

Creating dsmr_remote ... done
Attaching to dsmr_remote
dsmr_remote    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
dsmr_remote    | [s6-init] ensuring user provided files have correct perms...exited 0.
dsmr_remote    | [fix-attrs.d] applying ownership & permissions fixes...
dsmr_remote    | [fix-attrs.d] done.
dsmr_remote    | [cont-init.d] executing container initialization scripts...
dsmr_remote    | [cont-init.d] 10-adduser: executing... 
dsmr_remote    | usermod: no changes
dsmr_remote    | 
dsmr_remote    | -------------------------
dsmr_remote    | User UID: 803
dsmr_remote    | User GID: 803
dsmr_remote    | -------------------------
dsmr_remote    | 
dsmr_remote    | [cont-init.d] 10-adduser: exited 0.
dsmr_remote    | [cont-init.d] 20-set-app-defaults: executing... 
[ INFO ] DSMR Reader Reader release: 5.9.0
[ INFO ] DSMR Reader Reader Docker release: 2022.12.02
[ INFO ] Ensure permissions...
[ INFO ] Setting architecture requirements...
[ INFO ] X64 Architecture
[ INFO ] Verifying if the DSMR Reader web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...
dsmr_remote    | nc: getaddrinfo: Try again
Testing database connectivity: 1 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 2 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 3 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 4 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 5 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 6 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 7 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 8 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 9 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 10 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 11 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 12 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 13 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 14 second(s) of 30 seconds...nc: getaddrinfo: Try again
Testing database connectivity: 15 second(s) of 30 seconds...nc: getaddrinfo: Try again
