### ISSUE TITLE
unraid docker start niet meer op

### ISSUE THREAD

**Issue by Ruvetuve** [xirixiz/dsmr-reader-docker#313]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

Ik krijg de volgende log uit unraid, waarna de container direct afsluit. Ik kan mij herinneren dat ik gister de image geupdate heb. Als ik de debug env variable toevoeg aan de startup zie ik nergens debug logs..

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------
User UID: 803
User GID: 803
-------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing...
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.

0 static files copied to '/var/www/dsmrreader/static', 559 unmodified.
Updating password of superuser "admin"
Deactivating any other existing superusers
[cont-init.d] 20-set-app-defaults: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

### Expected behaviour

startup van de docker of log files

### Actual behaviour

container stopt gelijk na starten

### Steps to reproduce

Start de docker

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 38
  Running: 31
  Paused: 0
  Stopped: 7
 Images: 38
 Server Version: 20.10.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.28-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
 Name: Nuc
 ID: F3E4:UWT3:OWU6:CBZ3:T44O:65B6:YS3K:VBHZ:7LAD:NUTT:A5UO:ACLQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Version

none

### Docker compose

```yaml
none
```

### Container logs

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------
User UID: 803
User GID: 803
-------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing...
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.

0 static files copied to '/var/www/dsmrreader/static', 559 unmodified.
Updating password of superuser "admin"
Deactivating any other existing superusers
[cont-init.d] 20-set-app-defaults: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`
