### ISSUE TITLE
Unable to boot after recent upgrade

### ISSUE THREAD

**Issue by Diondk** [xirixiz/dsmr-reader-docker#315]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I updated dsmr reader to the latest version that has been published today and i get this error.

I am running on unraid 

### Expected behaviour

Should start normally

### Actual behaviour

Fails to start

### Steps to reproduce

upgrade from the version in december to the latest

### Docker info

```yaml
n/a i am running unraid
```

### Version

Linux Tower 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz GenuineIntel GNU/Linux

### Docker compose

```yaml
na
```

### Container logs

[2023-01-30 10:49:00 +0100] [771] [INFO] Starting gunicorn 20.1.0
[2023-01-30 10:49:00 +0100] [771] [INFO] Listening at: unix:/tmp/gunicorn--dsmr_webinterface.socket (771)
[2023-01-30 10:49:00 +0100] [771] [INFO] Using worker: sync
[2023-01-30 10:49:00 +0100] [776] [INFO] Booting worker with pid: 776
[2023-01-30 10:49:00 +0100] [776] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dsmrreader/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dsmrreader/settings.py", line 4, in <module>
    from dsmrreader.config.production import *
  File "/app/dsmrreader/config/production.py", line 1, in <module>
    from dsmrreader.config.defaults import *
  File "/app/dsmrreader/config/defaults.py", line 16, in <module>
    DSMRREADER_LOGLEVEL = config(
                          ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decouple.py", line 245, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decouple.py", line 101, in get
    return cast(value)
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decouple.py", line 309, in __call__
    raise ValueError((
ValueError: Value not in list: 'warning'; valid values are ['DEBUG', 'WARNING', 'ERROR']
[2023-01-30 10:49:00 +0100] [776] [INFO] Worker exiting (pid: 776)
[2023-01-30 10:49:00 +0100] [771] [INFO] Shutting down: Master
[2023-01-30 10:49:00 +0100] [771] [INFO] Reason: Worker failed to boot.
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...

**Comment by mupsje** [comment]
same here indeed

**Comment by xirixiz** [comment]
Hi, you need to provide a little more info. Can you share your docker-compose file?
@mupsje do you also have unraid? Do you both use a tool like portainer?

**Comment by mupsje** [comment]
No, I use Docker Compose inside container station QNAP

``` 
version: '3'

services:
  dsmrdb:
    # When using Postgres, release 13.x is supported only
    # due to the limited availability of client packages, especially for arm32v7
    image: postgres:14-alpine
    container_name: dsmrdb
    restart: unless-stopped
    volumes:
      - /share/docker/dsmrdb:/var/lib/postgresql/data
    networks:
      vlan86:
        ipv4_address: ##################
    mac_address: ###############
    environment:
      - PUID=502
      - PGID=100
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    healthcheck:
      # postgres is the default user, please update with
      # the DJANGO_DATABASE_USER used for dsmr-reader-docker
      # default for DSMR Reader is dsmrreader
      test: [ "CMD-SHELL", "pg_isready -U dsmrreader" ]
      interval: 10s
      timeout: 5s
      retries: 10

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      dsmrdb:
        condition: service_healthy
    container_name: dsmr
    links:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/docker/dsmr_backups:/app/backups
    networks:
      vlan86:
        ipv4_address: ##############
    mac_address: ################
    environment:
      - PUID=502
      - PGID=100
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=###############
    ports:
      - 7777:80
      - 7779:443
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    # healthcheck:
    #   disable: true
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-Lsf",
          "http://127.0.0.1/about",
          "-o",
          "/dev/null",
          "-w",
          "HTTP_%{http_code}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  dsmrdb: null
  dsmrdb_backups: null
  
networks:
  vlan20:
    name: qnet-static-vlan20
    external: true
  vlan30:
    name: qnet-static-vlan30
    external: true
  vlan40:
    name: qnet-static-vlan40
    external: true
  vlan86:
    name: qnet-static-vlan86
    external: true
    
``` 

Log output:




2023/01/30 11:21:07 [crit] 301#301: *13 connect() to unix:///tmp/gunicorn--dsmr_webinterface.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /about HTTP/1.1", upstream: "http://unix:///tmp/gunicorn--dsmr_webinterface.socket:/about", host: "127.0.0.1"
127.0.0.1 - - [30/Jan/2023:11:21:07 +0100] "GET /about HTTP/1.1" 502 150 "-" "curl/7.83.1" "-"
Starting DSMR Reader - datalogger...
Starting DSMR Reader - backend...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - backend...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - backend...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - backend...
Starting DSMR Reader - backend...
Starting DSMR Reader - datalogger...
Starting DSMR Reader - webinterface...
Starting DSMR Reader - webinterface...
