### ISSUE TITLE
Container does not start: 20-set-app-defaults: line 213: syntax error near unexpected token `}'

### ISSUE THREAD

**Issue by mrtnbr** [xirixiz/dsmr-reader-docker#333]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating to 5.10.3-2023.04.02, I get the following error when starting the container. Reverting to 5.10.3-2023.04.01 works again.

### Expected behaviour

I would expect the container to start without problems.

### Actual behaviour

Container does not start.

### Steps to reproduce

Upgrade the docker image to latest/5.10.3-2023.04.02 and start the container.

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 31
  Running: 31
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.58GiB
 Name: <snip>
 ID: <snip>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```


### Version

Docker Compose version v2.17.2

Linux hostname 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux



### Docker compose

```yaml
-
```

### Container logs

```
dsmr-reader  | usermod: no changes
dsmr-reader  | 
dsmr-reader  | -------------------------
dsmr-reader  | User UID: 803
dsmr-reader  | User GID: 803
dsmr-reader  | -------------------------
dsmr-reader  | 
dsmr-reader  | [cont-init.d] 10-adduser: exited 0.
dsmr-reader  | [cont-init.d] 20-set-app-defaults: executing... 
dsmr-reader  | /var/run/s6/etc/cont-init.d/20-set-app-defaults: line 213: syntax error near unexpected token `}'
dsmr-reader  | /var/run/s6/etc/cont-init.d/20-set-app-defaults: line 213: `}'
dsmr-reader  | [cont-init.d] 20-set-app-defaults: exited 2.
dsmr-reader  | [cont-finish.d] executing container finish scripts...
dsmr-reader  | [cont-finish.d] done.
dsmr-reader  | [s6-finish] waiting for services.
dsmr-reader  | [s6-finish] sending all processes the TERM signal.
dsmr-reader  | [s6-finish] sending all processes the KILL signal and exiting.
dsmr-reader  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
dsmr-reader  | [s6-init] ensuring user provided files have correct perms...exited 0.
dsmr-reader  | [fix-attrs.d] applying ownership & permissions fixes...
dsmr-reader  | [fix-attrs.d] done.
dsmr-reader  | [cont-init.d] executing container initialization scripts...
dsmr-reader  | [cont-init.d] 10-adduser: executing... 
dsmr-reader  | usermod: no changes
dsmr-reader  | 
dsmr-reader  | -------------------------
dsmr-reader  | User UID: 803
dsmr-reader  | User GID: 803
dsmr-reader  | -------------------------
dsmr-reader  | 
dsmr-reader  | [cont-init.d] 10-adduser: exited 0.
```

### Additional info

-
