### ISSUE TITLE
pg_dump: error :aborting because of server version mismatch

### ISSUE THREAD

**Issue by vangguppie** [xirixiz/dsmr-reader-docker#341]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I moved to docker dsmrreader recently with a fresh setup on a raspberry pi 3b+ after having issues with my dsmrreader setup (file system corruption)
 
Followed the instructions of "run with docker run" and got dsmrreader container(dsmr) working with postgressql in an own container (dsmrdb).

the logfile of the dsmr container is showing a error:
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.0 (Debian 16.0-1.pgdg120+1); pg_dump version: 15.2
2023-10-07 17:29:41,452 ERROR    schedule     execute_scheduled_processes      39 | (AttributeError) dsmr_backup.services.backup.run errored: 'NoneType' object has no attribute 'read' 

### Expected behaviour

executing of pgdump command

### Actual behaviour

proces not running because of error

### Steps to reproduce

1. change generate day and hour statitics to a date in the past. (run now)
2. error in the log files

### Docker info

```yaml
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 909.6MiB
 Name: pi-dock1
 ID: 472d520e-baa7-4093-80af-106eb19d8f63
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

### Docker compose

```yaml
no docker compose available
```

### Container logs

pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.0 (Debian 16.0-1.pgdg120+1); pg_dump version: 15.2
2023-10-07 17:29:41,452 ERROR    schedule     execute_scheduled_processes      39 | (AttributeError) dsmr_backup.services.backup.run errored: 'NoneType' object has no attribute 'read'
