### ISSUE TITLE
MQTT werkt niet meer "Publish_split_topic_meter_statistics() failed: nextval: reached maximum" 

### ISSUE THREAD

**Issue by westy1969** [xirixiz/dsmr-reader-docker#358]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Sinds een aantal dagen werkt mqtt niet meer binnen DSMR, deze draait via een docker container.
melding in de container log is:
"Publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq"

Enig idee wat ik hier mee kan doen?

Heb al wat topic uitgezet, maar geen resultaat.

### Expected behaviour

MQTT topics worden verzonden

### Actual behaviour

Geen MQTT topics worden verzonden

"Publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq"

### Steps to reproduce

Herstart container

### Docker info

```yaml
xirixiz/dsmr-reader-docker:latest
```

### Version

* Docker compose version (type `docker-compose --version`): docker-compose version 1.23.2, build 1110ad01
* System info (type `uname -a`): Linux docker.local 4.18.0-532.el8.x86_64 #1 SMP Thu Dec 21 12:11:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
#################
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

#################
  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data
      - ./dsmr_backups:/app/backups  
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0
```

### Container logs

2024-04-15 22:47:29,418 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:30,269 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:31,119 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:32,300 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:33,147 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:34,328 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
2024-04-15 22:47:35,183 ERROR    apps         _on_dsmrreading_created_signal  159 | publish_split_topic_meter_statistics() failed: nextval: reached maximum value of sequence "dsmr_mqtt_message_id_seq" (2147483647)
