### ISSUE TITLE
DSMR-Reader losing conenction to datalogger since last update (:latest)

### ISSUE THREAD

**Issue by Mister86NL** [xirixiz/dsmr-reader-docker#359]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since the last update of the docker container yesterday the connection between DSMR-reader and the datalogger (base on ESP) is unstable:

   No recent readings received   (an hour ago)

After restarting the docker container, it is stable for some time. It occurs 3 times now since yesterday, running DSMR-Reader since Aug 2020, never saw this behavior again. 

Also, the datalogger (ESP) is stable and reachable on both HTTP and TELNET when this error occurs.

### Expected behaviour

Stable connection, as the last ~3 years :)

### Actual behaviour

DSMR-Reader gives en error on the 'About' Page and via Pushover API:

No recent readings received   (an hour ago)

### Steps to reproduce

none.

### Docker info

```yaml
1337@UnraidSERVER:~# docker info
Client:
 Version:    24.0.9
 Context:    default
 Debug Mode: false

Server:
 Containers: 30
  Running: 29
  Paused: 0
  Stopped: 1
 Images: 25
 Server Version: 24.0.9
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d200ca3811ff6096eb8
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.74-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: UnraidSERVER
 ID: e87DD754-643f-443f-b092-2823ef62bca3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

### Version

1337@UnraidSERVER:~# uname -a
Linux UnraidSERVER 6.1.74-Unraid #1 SMP PREEMPT_DYNAMIC Fri Feb  2 11:06:32 PST 2024 x86_64 Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz GenuineIntel GNU/Linux

### Docker compose

```yaml
n/a, using Unraid
```

### Container logs

127.0.0.1 - - [16/Apr/2024:19:40:58 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:41:13 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:41:28 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:41:43 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:41:59 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:42:14 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:42:29 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:42:45 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:43:00 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:43:15 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:43:31 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:43:46 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:44:01 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:44:16 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:44:32 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:44:47 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"
127.0.0.1 - - [16/Apr/2024:19:45:02 +0200] "GET /about HTTP/1.1" 200 13437 "-" "curl/8.5.0" "-"

### Additional info

Please tell me how to provide some more logs, container logs are the wrong level, maybe on the admin pages?

Debug info:

DSMR-READER
    App | Python | Database                                                      v5.11 | v3.11.9 | postgresql
    BE sleep | DL sleep | Retention | Override                                    1.0s | 3.0s | 2232h | False
    Latest telegram version read | Parser settings                                                 "50" | "4"

DATA
    Telegrams total (est.)                                                                            1843579
    Consumption records electricity | gas (est.)                                               192844 | 85853

POSTGRESQL SIZE OF LARGEST TABLES (> 500 MB)
    public.dsmr_datalogger_dsmrreading                                                                 761 MB
