### ISSUE TITLE
Not receiving telegrams anymore

### ISSUE THREAD

**Issue by jantje88** [xirixiz/dsmr-reader-docker#36]
I am using this docker on a NUC (running Ubuntu Server) with this P1/USB cable https://www.sossolutions.nl/slimme-meter-kabel connected to ttyUSB0: https://i.imgur.com/kWyLRej.png

Since a few days, no telegrams are received anymore and I am not sure why.
In my docker compose and in the datalogger configuration, `/dev/ttyUSB0/` is entered: https://i.imgur.com/Q7jS2Ca.png

docker-compose:

```
  dsmr:
    image: xirixiz/dsmr-reader-docker
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

This was working fine for almost 1 week, but out of the blue, no telegrams anymore.
Any clue what could be the problem?
