### ISSUE TITLE
No new readings after meter change 

### ISSUE THREAD

**Issue by Martinvdm** [xirixiz/dsmr-reader-docker#364]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Na een meter wissel van dsmr2/3 naar dsmr4/5 leest de dsmr geen data meer. Nou zou het ook aan https://github.com/xirixiz/dsmr-reader-docker/issues/359 kunnen liggen, zelfde foutmelding, echter draai ik al 2024.04.03. Ook container opnieuw aangemaakt, helaas.
In de config uiteraard de data logger op dsmr4/5 gezet.

### Expected behaviour

werkende readings 

### Actual behaviour

Geen readings

### Steps to reproduce

Nvt

### Docker info

```yaml
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 28
  Running: 26
  Paused: 0
  Stopped: 2
 Images: 38
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-166-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.648GiB
 Name: domotica
 ID: 2a62a0ba-3967-4042-9de3-be1b7e11487a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ****
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

### Docker compose

```yaml
dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: DSMR-Reader
    links:
      - dsmrdb
    restart: always
    depends_on:
      - dsmrdb
    environment:
      - TZ=Europe/Amsterdam
      - SD_LOGLEVEL=info
      #- DSMRREADER_LOGLEVEL=DEBUG
      - SD_AUTORESTART_DATALOGGER=true
      - DB_HOST=dsmrdb
      - DB_USER=${DSMR_USER}
      - DB_PASS=${DSMR_PASS}
      - DB_PORT=5432
      - SD_USER=root
      - SD_GROUP=root
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=****
      - VIRTUAL_HOST=localhost
    ports:
      - 8888:80
      - 8889:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-Lsf",
          "http://127.0.0.1/about",
          "-o",
          "/dev/null",
          "-w",
          "HTTP_%{http_code}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

### Container logs
```
2024-07-11 18:18:51,042 ERROR    mixins       run_once                        107 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
  File "/app/dsmr_backend/mixins.py", line 96, in run_once
    self.run(data=self.data, **options)
  File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
    telegram = next(self.telegram_generator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 51, in read_telegram
    raise RuntimeError(
RuntimeError: It took too long to detect a telegram. Check connection params. Bytes currently in buffer: 0
Starting DSMR Reader - datalogger...
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
```
