### ISSUE TITLE
Backup MariaDB is not wokring anymore

### ISSUE THREAD

**Issue by aelsenaar** [xirixiz/dsmr-reader-docker#373]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After upgrading to the latest version of the docker image I get the following error in de logs:

`2025-01-14 19:01:58,296 ERROR    schedule     execute_scheduled_processes      39 | (FileNotFoundError) dsmr_backup.services.backup.run errored: [Errno 2] No such file or directory: 'mysqldump'`

When checking the volume with all the schema backups, the latest backup files are all of size 0.

```
root@dsmr_reader_docker:/app/backups# ls -lot
total 361908
-rw-r--r-- 1 app        0 Jan 14 19:06 dsmrreader-mysql-backup-Tuesday.sql
-rw-r--r-- 1 app        0 Jan 14 00:59 dsmrreader-mysql-backup-Monday.sql
-rw-r--r-- 1 app        0 Jan 12 23:59 dsmrreader-mysql-backup-Sunday.sql
-rw-r--r-- 1 app        0 Jan 12 00:59 dsmrreader-mysql-backup-Saturday.sql
-rw-r--r-- 1 app        0 Jan 11 00:59 dsmrreader-mysql-backup-Friday.sql
-rw-r--r-- 1 app        0 Jan 10 00:59 dsmrreader-mysql-backup-Thursday.sql
-rw-r--r-- 1 app        0 Jan  9 00:59 dsmrreader-mysql-backup-Wednesday.sql
-rw-r--r-- 1 app 52856781 Jan  6 02:00 dsmrreader-mysql-backup-Monday.sql.gz
drwxrwxr-x 4 app     4096 Jan  6 02:00 archive
-rw-r--r-- 1 app 52887836 Jan  5 02:00 dsmrreader-mysql-backup-Sunday.sql.gz
-rw-r--r-- 1 app 52941180 Jan  4 02:00 dsmrreader-mysql-backup-Saturday.sql.gz
-rw-r--r-- 1 app 52982376 Jan  3 02:00 dsmrreader-mysql-backup-Friday.sql.gz
-rw-r--r-- 1 app 52981448 Jan  2 02:00 dsmrreader-mysql-backup-Thursday.sql.gz
-rw-r--r-- 1 app 52978891 Jan  1 02:00 dsmrreader-mysql-backup-Wednesday.sql.gz
-rw-r--r-- 1 app 52918973 Dec 31 02:00 dsmrreader-mysql-backup-Tuesday.sql.gz
```

### Expected behaviour

The mysqldump program can be found to create a valid backup.

### Actual behaviour

No backup is created bacause the mysqldump is not available.

### Steps to reproduce

1. Use MariaDB / MySQL as database
2. Upgrade to the latest version of the docker image
3. Start and run the container normaly

### Docker info

```yaml
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 7
  Paused: 0
  Stopped: 8
 Images: 9
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: u2yhk5cma9l6d26ejbf0ej001
  Is Manager: true
  ClusterID: odteq521d6hnf18wx77k04mun
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.41
  Manager Addresses:
   192.168.1.41:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.13GiB
 Name: jupiter
 ID: 3efae96b-568f-43ee-901c-a11e68cf7105
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Version

* Docker compose version (type `docker-compose --version`):
Portainer version 2.51.5 / Compose version 3.7

* System info (type `uname -a`):
Linux jupiter 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Docker compose

```yaml
n.a.
```

### Container logs

```
10.0.0.28 - - [14/Jan/2025:19:13:12 +0100] "POST /api/v1/datalogger/dsmrreading HTTP/1.1" 201 0 "-" "python-requests/2.27.1" "-"
925
127.0.0.1 - - [14/Jan/2025:19:13:13 +0100] "GET /about HTTP/1.1" 302 0 "-" "curl/8.11.1" "-"
926
127.0.0.1 - - [14/Jan/2025:19:13:13 +0100] "GET /admin/login/?next=/about HTTP/1.1" 200 2196 "-" "curl/8.11.1" "-"
927
2025-01-14 19:13:13,136 ERROR    schedule     execute_scheduled_processes      39 | (FileNotFoundError) dsmr_backup.services.backup.run errored: [Errno 2] No such file or directory: 'mysqldump' 
928
10.0.0.28 - - [14/Jan/2025:19:13:13 +0100] "POST /api/v1/datalogger/dsmrreading HTTP/1.1" 201 0 "-" "python-requests/2.27.1" "-"
929
10.0.0.28 - - [14/Jan/2025:19:13:14 +0100] "POST /api/v1/datalogger/dsmrreading HTTP/1.1" 201 0 "-" "python-requests/2.27.1" "-"
930

```
