### ISSUE TITLE
SSL cert from host into docker container

### ISSUE THREAD

**Issue by RualdOrdelman** [xirixiz/dsmr-reader-docker#43]
Thanks for creating this great container. Is it possible to create a docker option to give up an local SSL cert that can be used inside the container? 

For example, I want to use something like this in the docker-compose

```
version: '3'
services:
 unifi-controller-goofball:
   container_name: unifi.controller.goofball
   image: goofball222/unifi:latest
   restart: unless-stopped
   network_mode: host
   volumes:
     - '/docker/unifi-goofball/kpn_config/config.gateway.json:/usr/lib/unifi/data/sites/default/config.gateway.json'
     - '/usr/share/hassio/ssl:/usr/lib/unifi/cert'
     - './data:/usr/lib/unifi/data'
     - './logs:/usr/lib/unifi/logs'
   environment:
     - TZ=Europe/Amsterdam
     - RUNAS_UID0=true
```
