### ISSUE TITLE
Postgres port

### ISSUE THREAD

**Issue by Gerben321** [xirixiz/dsmr-reader-docker#44]
I'm interested in trying the DSMR reader, and I would like to run it on my Synology NAS on Docker since I've got all my smart home stuff running there. I've got the Postgres Docker running already. Tried connecting to it via pgAdmin, and that seems to work great. I've made a database for DSMR so I'm all set, right?

Well, not really, since I can't seem to get this Docker running. I've downloaded it from the Docker GUI in DSM and downloaded it. I've then entered the right values in the environment settings. The onyl thing is that I have a different Postgres DB port since 5432 was already used. I've changed it to 6432 and I am able to connect via pgAdmin.

But how do I enter that here? I've tried ip:6432 but when I check the log it keeps doing this and reboots:

[ INFO ] Checking if the DSMR web credential variables have been set...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Verifying if Postgres in running...

There's obviously no hardware connected, I am trying to fill the data via an external Raspberry 1 via the API. Is there a hidden environment setting or something? Tried PORT and DB_PORT as well.

Also, how do I set it to persist data on a specific folder I want? In all other Dockers I have a path I can set where data is saved.

**Comment by xirixiz** [comment]
For mapping your data:
```
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    network_mode: bridge
    volumes:
      - ./data/dsmr/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
```
I use this myself to use another port:
```
  dsmr:
    image: xirixiz/dsmr-reader-docker
    container_name: dsmr
    network_mode: bridge
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    volumes:
      - ./data/dsmr/backups:/dsmr/backups
    restart: always
    environment:
      - DB_PORT=4444
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

Hope this helps.
You could also run ```docker exec -ti <container id> bash``` and the verify whether the DB_PORT variable has been set correctly.
