### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by RezzZ** [xirixiz/dsmr-reader-docker#46]
Tried running dsmr on my raspberrypi 3b+ (ARMv7/8).

I keep receiving the following error:
```
standard_init_linux.go:207: exec user process caused "exec format error"
```
and the container keeps rebooting.

I use almost an identical copy of your compose file. Only difference is 
1. My mapped volumes are hard
2. I omitted the commented out line `#    build: .`
3. I point to the ARMv8 version of your image
4. I skipped exposing port 433
5. Restart policy is unless-stopped:
```
version: '3.6'
services:

  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: unless-stopped
    volumes:
      - /opt/dsmrdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:arm64v8-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    volumes:
      - /opt/dsmrdb:/var/lib/postgresql/data
      - /opt/dsmr_backups:/home/dsmr/app/backups
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

 Any thoughts?

edit:
ohh and yes, my user is part of the docker user group. dsmrdb is running fine and awaiting connection (and I'm already running other images like portainer, homeassistant, mariadb, influxdb, unifi)
