### ISSUE TITLE
after upgrading, dsmr container fails due to supervisord issues

### ISSUE THREAD

**Issue by kooskaspers** [xirixiz/dsmr-reader-docker#61]
after pulling the latest image (9e07f0609aac) I'm encountering some issues:

```
[ INFO ] Starting supervisord...
dsmr      | /usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
dsmr      |   'Supervisord is running as root and it is searching '
dsmr      | Error: Format string '%(ENV_SD_USER)s' for 'supervisord.user' contains names ('ENV_SD_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_USER, ENV_DSMR_EMAIL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_GET_PIP_SHA256, ENV_PYTHON_GET_PIP_URL, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SHLVL, ENV_VIRTUAL_HOST, ENV__, here
dsmr      | For help, use /usr/bin/supervisord -h
dsmr exited with code 2
```
With tag :2.2.1 the dsmr container works fine.
I'm using a postgress image as db service.

docker-compose:

```
version: "3.6"
services:
  dsmrdb:
#    image: 084ec18124c8 
    image: postgres
    container_name: dsmrdb
    user: 1000:1000
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data
      - ./dsmrdb_backups:/dsmr/backups
    restart: always
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker
    container_name: dsmr
    user: root
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links: #deze feature schijnt depricated te worden
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./data/dsmr-webinterface.conf:/etc/nginx/conf.d/dsmr-webinterface.conf
      - ./data/htpasswd:/etc/nginx/htpasswd

```
