### ISSUE TITLE
Error: Format string '%(ENV_SD_START_DATALOGGER)s' for 'program:dsmr_datalogger.autostart' contains names ('ENV_SD_START_DATALOGGER')

### ISSUE THREAD

**Issue by llewy** [xirixiz/dsmr-reader-docker#71]
Using docker-compose I get this error:

`Error: Format string '%(ENV_SD_START_DATALOGGER)s' for 'program:dsmr_datalogger.autostart' contains names ('ENV_SD_START_DATALOGGER')`

I think I already added all of the SD_ enviroments to the docker-compose file:

```
version: '3'

services:
  dsmrdb:
    image: postgres
    container_name: dsmrdb
    volumes:
      - ~/dsmr_reader/dsmrdb:/var/lib/postgresql/data
      - ~/dsmr_reader/dsmrdb_backups:/home/dsmr/app/backups
    restart: always
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    networks:
      - dsmr_network

  dsmr:
    #build: .
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    links:
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
      - SD_USER=root
      - SD_GROUP=root   
      - SD_LOGLEVEL=info
      - SD_AUTOSTART_DATALOGGER=true
      - SD_AUTORESTART_DATALOGGER=true
      - SD_AUTOSTART_BACKEND=true
      - SD_AUTORESTART_BACKEND=true
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
    ports:
      - 2507:80
      - 2508:443
    #devices:
    #  - "/dev/virtualcom0:/dev/virtualcom0"
    volumes:
      - /dev/:/dev/
    networks:
      - dsmr_network

networks:
  dsmr_network:
    driver: bridge
```
